/// @desc scr_opcode_hex(op_key)
/// Returns a 2-char uppercase hex string for the given lowercase mnemonic key.
/// Returns "??" if not found.
function scr_opcode_hex(_key) {
    static _hex_map = {
        "brk": "00", "nop": "EA",
        "lda_imm": "A9", "ldx_imm": "A2", "ldy_imm": "A0",
        "lda_zp":  "A5", "ldx_zp":  "A6", "ldy_zp":  "A4",
        "lda_zpx": "B5", "ldx_zpy": "B6", "ldy_zpx": "B4",
        "lda_abs": "AD", "ldx_abs": "AE", "ldy_abs": "AC",
        "lda_abx": "BD", "ldx_aby": "BE", "ldy_abx": "BC",
        "lda_aby": "B9", "lda_izx": "A1", "lda_izy": "B1",
        "sta_zp":  "85", "stx_zp":  "86", "sty_zp":  "84",
        "sta_zpx": "95", "stx_zpy": "96", "sty_zpx": "94",
        "sta_abs": "8D", "stx_abs": "8E", "sty_abs": "8C",
        "sta_abx": "9D", "sta_aby": "99", "sta_izx": "81", "sta_izy": "91",
        "tax": "AA", "tay": "A8", "tsx": "BA", "txa": "8A", "tya": "98", "txs": "9A",
        "adc_imm": "69", "inx": "E8", "iny": "C8",
        "adc_zp":  "65", "dex": "CA", "dey": "88",
        "adc_zpx": "75", "inc_zp": "E6", "dec_zp": "C6",
        "adc_abs": "6D", "inc_abs": "EE", "dec_abs": "CE",
        "adc_abx": "7D", "inc_abx": "FE", "dec_abx": "DE",
        "adc_aby": "79", "adc_izx": "61", "adc_izy": "71",
        "sbc_imm": "E9", "sbc_zp":  "E5", "sbc_abs": "ED",
        "sbc_zpx": "F5", "sbc_abx": "FD", "sbc_aby": "F9",
        "sbc_izx": "E1", "sbc_izy": "F1",
        "and_imm": "29", "cmp_imm": "C9", "bit_zp": "24",
        "and_zp":  "25", "cpx_imm": "E0", "cpy_imm": "C0",
        "and_abs": "2D", "cpx_zp":  "E4", "cpy_zp":  "C4",
        "ora_imm": "09", "ora_zp":  "05", "ora_abs": "0D",
        "eor_imm": "49", "eor_zp":  "45", "eor_abs": "4D",
        "ora_zpx": "15", "ora_abx": "1D", "ora_aby": "19",
        "and_zpx": "35", "and_abx": "3D", "and_aby": "39",
        "eor_zpx": "55", "eor_abx": "5D", "eor_aby": "59",
        "bit_abs": "2C", "cpx_abs": "EC", "cpy_abs": "CC",
        "cmp_zp":  "C5", "cmp_abs": "CD", "cmp_zpx": "D5",
        "cmp_abx": "DD", "cmp_aby": "D9", "cmp_izx": "C1", "cmp_izy": "D1",
        "and_izx": "21", "and_izy": "31",
        "ora_izx": "01", "ora_izy": "11",
        "eor_izx": "41", "eor_izy": "51",
        "inc_zpx": "F6", "dec_zpx": "D6",
        "asl_a":   "0A", "rol_a":   "2A", "ror_a":   "6A",
        "asl_zp":  "06", "rol_zp":  "26", "ror_zp":  "66",
        "asl_abs": "0E", "rol_abs": "2E", "ror_abs": "6E",
        "lsr_a":   "4A", "lsr_zp":  "46", "lsr_abs": "4E",
        "asl_zpx": "16", "asl_abx": "1E",
        "lsr_zpx": "56", "lsr_abx": "5E",
        "rol_zpx": "36", "rol_abx": "3E",
        "ror_zpx": "76", "ror_abx": "7E",
        "jmp":     "4C", "jmp_abs": "4C", "jsr": "20", "rts": "60",
        "bne": "D0", "beq": "F0", "jmp_ind": "6C",
        "bcc": "90", "bcs": "B0", "bpl": "10", "bmi": "30",
        "bvc": "50", "bvs": "70", "rti": "40",
        "lax_zp":  "A7", "sax_zp":  "87",
        "dcp_abs": "CF", "isc_abs": "EF", "rla_abs": "2F",
        "slo_abs": "0F", "sre_abs": "4F",
        "lax_abs": "AF", "lax_aby": "BF", "lax_zpy": "B7",
        "lax_izx": "A3", "lax_izy": "B3",
        "sax_abs": "8F", "sax_zpy": "97", "sax_izx": "83",
        "dcp_zp":  "C7", "dcp_zpx": "D7", "dcp_abx": "DF",
        "dcp_aby": "DB", "dcp_izx": "C3", "dcp_izy": "D3",
        "isc_zp":  "E7", "isc_zpx": "F7", "isc_abx": "FF",
        "isc_aby": "FB", "isc_izx": "E3", "isc_izy": "F3",
        "rla_zp":  "27", "rla_zpx": "37", "rla_abx": "3F",
        "rla_aby": "3B", "rla_izx": "23", "rla_izy": "33",
        "rra_zp":  "67", "rra_zpx": "77", "rra_abs": "6F",
        "rra_abx": "7F", "rra_aby": "7B", "rra_izx": "63", "rra_izy": "73",
        "slo_zp":  "07", "slo_zpx": "17", "slo_abx": "1F",
        "slo_aby": "1B", "slo_izx": "03", "slo_izy": "13",
        "sre_zp":  "47", "sre_zpx": "57", "sre_abx": "5F",
        "sre_aby": "5B", "sre_izx": "43", "sre_izy": "53",
        "anc_imm": "0B", "anc2_imm": "2B", "alr_imm": "4B",
        "arr_imm": "6B", "axs_imm": "CB",
        "nop_imm": "80", "nop_zp":  "04", "nop_zpx": "14",
        "nop_abs": "0C", "nop_abx": "1C",
        "clc": "18", "sec": "38", "sei": "78", "cli": "58",
        "pha": "48", "pla": "68", "php": "08", "plp": "28",
        "clv": "B8", "cld": "D8", "sed": "F8",
        "label": "00", "comment": "00", "org": "00",
        "byte": "00", "word": "00",
        "sta_abs_x": "9D", "sta_abs_y": "99",
        "lda_abs_x": "BD", "lda_abs_y": "B9",
        "adc_zp_x":  "75", "adc_abs_x": "7D", "adc_abs_y": "79",
        "adc_ind_x": "61", "adc_ind_y": "71",
        "sbc_zp_x":  "F5", "sbc_abs_x": "FD", "sbc_abs_y": "F9",
        "sbc_ind_x": "E1", "sbc_ind_y": "F1",
        "and_zp_x":  "35", "and_abs_x": "3D", "and_abs_y": "39",
        "ora_zp_x":  "15", "ora_abs_x": "1D", "ora_abs_y": "19",
        "eor_zp_x":  "55", "eor_abs_x": "5D", "eor_abs_y": "59",
        "inc_abs_x": "FE", "dec_abs_x": "DE",
        "asl_zp_x":  "16", "asl_abs_x": "1E",
        "lsr_zp_x":  "56", "lsr_abs_x": "5E",
        "rol_zp_x":  "36", "rol_abs_x": "3E",
        "ror_zp_x":  "76", "ror_abs_x": "7E",
        "lda_iny":   "B1", "jsr_lab":   "20",
        "lda_lab_lo": "A9", "lda_lab_hi": "A9",
        "ldy_lab_lo": "A0", "ldy_lab_hi": "A0",
        "ldx_lab_lo": "A2", "ldx_lab_hi": "A2",
        "store_lo": "8D", "store_hi": "8D",
        "byte_lab_lo": "00", "byte_lab_hi": "00",
        "lda_lab": "AD", "sta_lab": "8D", "stx_lab": "8E", "sty_lab": "8C",
        "ldx_lab": "AE", "ldy_lab": "AC", "inc_lab": "EE", "dec_lab": "CE",
        "cmp_lab": "CD", "ora_lab": "0D", "sbc_lab": "ED",
        "sta_iny":  "91",
    };

    if (variable_struct_exists(_hex_map, _key)) {
        return _hex_map[$ _key];
    }
    return "??";
}