/// @function scr_write_reu_launcher(_target_path, _reu_path)
/// @description Writes a small launcher script next to an exported program so
///              it runs in VICE with its own REU image already attached.
///
/// F5 never needed this: scr_launch_vice builds the command line itself and
/// passes -reu -reusize -reuimage. A manually exported PRG has nobody to do
/// that, so the image has to be attached by hand - and an emulator still
/// holding an image from an earlier build will run the new program against
/// stale data, which looks exactly like a packing bug and is not one.
///
/// The launcher uses paths relative to itself (%~dp0 on Windows, $DIR on
/// macOS), so the exported folder can be moved, zipped, or sent to a tester
/// and still work. Nothing in VICE's own configuration is touched.
///
/// @param {string} _target_path  Absolute path to the exported .prg or .d64
/// @param {string} _reu_path     Absolute path to the .reu image beside it
/// @returns {string} Absolute path to the launcher written, or "" on failure.

function scr_write_reu_launcher(_target_path, _reu_path)
{
    if (_target_path == "" || _reu_path == "") {
        return "";
    }

    var _dir       = filename_path(_target_path);
    var _target_nm = filename_name(_target_path);
    var _reu_nm    = filename_name(_reu_path);
    var _stem      = filename_change_ext(_target_nm, "");

    // Baked in as the fallback only; PATH is tried first so the same file
    // works on a machine that keeps VICE somewhere else. On macOS this is the
    // x64sc .app BUNDLE the user picked (see Alarm_0), not an executable, so
    // the macOS launcher below starts it with "open -a" rather than running
    // it directly - a .app is a directory and cannot be exec'd.
    var _vice = global.vice_path_cache;

    var _out  = "";
    var _text = "";

    if (os_type == os_macosx) {
        var _lf = chr(10);
        _out = _dir + _stem + "_run.command";
        _text  = "#!/bin/sh" + _lf;
        _text += "# ----------------------------------------------------------" + _lf;
        _text += "# Generated by C64 Dev Machine." + _lf;
        _text += "# Runs " + _target_nm + " in VICE with " + _reu_nm + " attached" + _lf;
        _text += "# as the REU image. Paths are relative to this file, so this" + _lf;
        _text += "# folder can be moved or zipped and it still works." + _lf;
        _text += "#" + _lf;
        _text += "# A command-line x64sc on PATH (e.g. Homebrew's vice) is used" + _lf;
        _text += "# first. Otherwise the x64sc.app below is started with open -a," + _lf;
        _text += "# the same way C64 Dev Machine launches it. Edit VICE_APP if" + _lf;
        _text += "# you keep VICE somewhere else." + _lf;
        _text += "#" + _lf;
        _text += "# Received this folder from someone else? macOS will block a" + _lf;
        _text += "# downloaded .command the first time: right-click it, choose" + _lf;
        _text += "# Open, and confirm." + _lf;
        _text += "# ----------------------------------------------------------" + _lf;
        _text += "DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"" + _lf;
        _text += "REU=\"$DIR/" + _reu_nm + "\"" + _lf;
        _text += "PRG=\"$DIR/" + _target_nm + "\"" + _lf;
        _text += "VICE_APP=\"" + _vice + "\"" + _lf;
        _text += "" + _lf;
        _text += "VICE_BIN=\"$(command -v x64sc 2>/dev/null)\"" + _lf;
        _text += "if [ -n \"$VICE_BIN\" ]; then" + _lf;
        _text += "  exec \"$VICE_BIN\" -reu -reusize 16384 -reuimage \"$REU\" -autostart \"$PRG\"" + _lf;
        _text += "fi" + _lf;
        _text += "" + _lf;
        _text += "if [ -d \"$VICE_APP\" ]; then" + _lf;
        _text += "  xattr -dr com.apple.quarantine \"$VICE_APP\" 2>/dev/null" + _lf;
        _text += "  /usr/bin/open -n -a \"$VICE_APP\" --args -reu -reusize 16384 -reuimage \"$REU\" -autostart \"$PRG\"" + _lf;
        _text += "  exit 0" + _lf;
        _text += "fi" + _lf;
        _text += "" + _lf;
        _text += "echo \"Could not find VICE. Edit VICE_APP in this file to point at x64sc.app.\"" + _lf;
        _text += "exit 1" + _lf;
    } else {
        // cmd.exe needs CRLF. A .bat saved with bare LF can mis-parse its own
        // control flow, which is how the MCP setup helper broke once already,
        // so the line ending is written explicitly rather than left to chance.
        var _crlf = chr(13) + chr(10);
        _out = _dir + _stem + "_run.bat";
        _text  = "@echo off" + _crlf;
        _text += "rem ----------------------------------------------------------" + _crlf;
        _text += "rem Generated by C64 Dev Machine." + _crlf;
        _text += "rem Runs " + _target_nm + " in VICE with " + _reu_nm + " attached" + _crlf;
        _text += "rem as the REU image. Paths are relative to this file, so this" + _crlf;
        _text += "rem folder can be moved or zipped and it still works." + _crlf;
        _text += "rem" + _crlf;
        _text += "rem VICE is taken from PATH first. Edit the fallback below if" + _crlf;
        _text += "rem you keep x64sc.exe somewhere else." + _crlf;
        _text += "rem ----------------------------------------------------------" + _crlf;
        _text += "setlocal" + _crlf;
        _text += "set \"VICE=\"" + _crlf;
        _text += "for %%I in (x64sc.exe) do set \"VICE=%%~$PATH:I\"" + _crlf;
        _text += "if \"%VICE%\"==\"\" set \"VICE=" + _vice + "\"" + _crlf;
        _text += "if not exist \"%VICE%\" (" + _crlf;
        _text += "  echo Could not find VICE. Edit the VICE= line in this file." + _crlf;
        _text += "  pause" + _crlf;
        _text += "  exit /b 1" + _crlf;
        _text += ")" + _crlf;
        _text += "\"%VICE%\" -reu -reusize 16384 -reuimage \"%~dp0" + _reu_nm + "\" -autostart \"%~dp0" + _target_nm + "\"" + _crlf;
        _text += "endlocal" + _crlf;
    }

    // Written through a buffer rather than file_text_* so the bytes on disk
    // are exactly the bytes above, line endings included.
    var _len = string_byte_length(_text);
    if (_len <= 0) {
        return "";
    }
    var _buf = buffer_create(_len, buffer_fixed, 1);
    buffer_write(_buf, buffer_text, _text);
    buffer_save(_buf, _out);
    buffer_delete(_buf);

    if (!file_exists(_out)) {
        show_debug_message("REU LAUNCHER: failed to write " + _out);
        return "";
    }

    // A .command the Finder will not run is no better than no launcher at
    // all, and GML has no chmod of its own. Exactly ONE spawn: libxprocess
    // can abort when several ProcessExecuteAsync calls land close together
    // (see the note in obj_workspace_manager Alarm_0).
    if (os_type == os_macosx) {
        ProcessExecuteAsync("/bin/chmod +x \"" + _out + "\"");
    }

    show_debug_message("REU LAUNCHER: wrote " + _out);
    return _out;
}
