/// @desc scr_opcode_helper()
/// Returns a struct with tooltip info for a given opcode mnemonic.
/// Fields: hex, bytes, cycles, format, mode, use
function scr_opcode_helper(_key) {
    static _map = {
        "brk":     { hex:"00", bytes:1, cycles:7,  format:"BRK",        mode:"Implied. Force break / software interrupt.",                        use:"Triggers IRQ handler. Used for debug breakpoints." },
        "nop":     { hex:"EA", bytes:1, cycles:2,  format:"NOP EA",      mode:"Implied. No operation.",                                           use:"Cycle padding, timing loops, patching code." },

        "lda_imm": { hex:"A9", bytes:2, cycles:2,  format:"LDA #$nn",    mode:"Immediate. Loads value directly into A.",                          use:"Set A to a known value before storing or comparing." },
        "lda_zp":  { hex:"A5", bytes:2, cycles:3,  format:"LDA $zz",     mode:"Zero Page. Loads A from address $00-$FF.",                         use:"Fast variable read from ZP — no high byte needed." },
        "lda_zpx": { hex:"B5", bytes:2, cycles:4,  format:"LDA $zz,X",   mode:"Zero Page,X. Reads A from ZP + X offset.",                        use:"Index into small ZP tables using X." },
        "lda_abs": { hex:"AD", bytes:3, cycles:4,  format:"LDA $hhll",   mode:"Absolute. Loads A from full 16-bit address.",                      use:"Read from hardware registers or variables in RAM." },
        "lda_abx": { hex:"BD", bytes:3, cycles:4,  format:"LDA $hhll,X", mode:"Absolute,X. Loads A from address + X.",                           use:"Walk through arrays or screen RAM with X as index." },
        "lda_aby": { hex:"B9", bytes:3, cycles:4,  format:"LDA $hhll,Y", mode:"Absolute,Y. Loads A from address + Y.",                           use:"Walk through arrays or screen RAM with Y as index." },
        "lda_izx": { hex:"A1", bytes:2, cycles:6,  format:"LDA ($zz,X)", mode:"(Indirect,X). Reads pointer from ZP+X, loads A.",                 use:"Rare but powerful — table of pointers in ZP." },
        "lda_izy": { hex:"B1", bytes:2, cycles:5,  format:"LDA ($zz),Y", mode:"(Indirect),Y. Uses ZP pointer + Y offset.",                       use:"Standard way to read through a pointer in ZP." },

        "ldx_imm": { hex:"A2", bytes:2, cycles:2,  format:"LDX #$nn",    mode:"Immediate. Loads value directly into X.",                          use:"Set loop counter or index before using X-indexed ops." },
        "ldx_zp":  { hex:"A6", bytes:2, cycles:3,  format:"LDX $zz",     mode:"Zero Page. Loads X from ZP address.",                             use:"Fast X load for indexing or loop control." },
        "ldx_zpy": { hex:"B6", bytes:2, cycles:4,  format:"LDX $zz,Y",   mode:"Zero Page,Y. Loads X from ZP + Y.",                              use:"Rare Y-indexed ZP load into X." },
        "ldx_abs": { hex:"AE", bytes:3, cycles:4,  format:"LDX $hhll",   mode:"Absolute. Loads X from full address.",                            use:"Read X from RAM variable or hardware port." },
        "ldx_aby": { hex:"BE", bytes:3, cycles:4,  format:"LDX $hhll,Y", mode:"Absolute,Y. Loads X from address + Y.",                          use:"Y-indexed table read into X." },

        "ldy_imm": { hex:"A0", bytes:2, cycles:2,  format:"LDY #$nn",    mode:"Immediate. Loads value directly into Y.",                          use:"Set Y counter or string index before a loop." },
        "ldy_zp":  { hex:"A4", bytes:2, cycles:3,  format:"LDY $zz",     mode:"Zero Page. Loads Y from ZP address.",                             use:"Fast Y load - often used for (ZP),Y pointer walks." },
        "ldy_zpx": { hex:"B4", bytes:2, cycles:4,  format:"LDY $zz,X",   mode:"Zero Page,X. Loads Y from ZP + X.",                              use:"X-indexed ZP load into Y." },
        "ldy_abs": { hex:"AC", bytes:3, cycles:4,  format:"LDY $hhll",   mode:"Absolute. Loads Y from full address.",                            use:"Read Y from RAM variable." },
        "ldy_abx": { hex:"BC", bytes:3, cycles:4,  format:"LDY $hhll,X", mode:"Absolute,X. Loads Y from address + X.",                          use:"X-indexed table read into Y." },

        "lda_lab_lo": { hex:"A9", bytes:2, cycles:2,  format:"LDA #<LABEL", mode:"Immediate. Loads the LOW byte of a label address into A.",    use:"Build a pointer - pair with #> and store both to ZP." },
        "lda_lab_hi": { hex:"A9", bytes:2, cycles:2,  format:"LDA #>LABEL", mode:"Immediate. Loads the HIGH byte of a label address into A.",   use:"Build a pointer - pair with #< and store both to ZP." },
        "ldx_lab_lo": { hex:"A2", bytes:2, cycles:2,  format:"LDX #<LABEL", mode:"Immediate. Loads the LOW byte of a label address into X.",    use:"Seed X with a table start without hardcoding the address." },
        "ldx_lab_hi": { hex:"A2", bytes:2, cycles:2,  format:"LDX #>LABEL", mode:"Immediate. Loads the HIGH byte of a label address into X.",   use:"Page number of a label - handy for page-aligned tables." },
        "ldy_lab_lo": { hex:"A0", bytes:2, cycles:2,  format:"LDY #<LABEL", mode:"Immediate. Loads the LOW byte of a label address into Y.",    use:"Seed Y with a label offset for (ZP),Y pointer walks." },
        "ldy_lab_hi": { hex:"A0", bytes:2, cycles:2,  format:"LDY #>LABEL", mode:"Immediate. Loads the HIGH byte of a label address into Y.",   use:"Page number of a label, held in Y." },

        "sta_zp":  { hex:"85", bytes:2, cycles:3,  format:"STA $zz",     mode:"Zero Page. Stores A to ZP address.",                              use:"Save A to a ZP variable — fastest store." },
        "sta_zpx": { hex:"95", bytes:2, cycles:4,  format:"STA $zz,X",   mode:"Zero Page,X. Stores A to ZP + X.",                               use:"Write into small ZP arrays using X." },
        "sta_abs": { hex:"8D", bytes:3, cycles:4,  format:"STA $hhll",   mode:"Absolute. Stores A to full 16-bit address.",                      use:"Write to VIC registers, colour RAM, or variables." },
        "sta_abx": { hex:"9D", bytes:3, cycles:5,  format:"STA $hhll,X", mode:"Absolute,X. Stores A at address + X.",                           use:"Fill arrays or screen RAM using X as index." },
        "sta_aby": { hex:"99", bytes:3, cycles:5,  format:"STA $hhll,Y", mode:"Absolute,Y. Stores A at address + Y.",                           use:"Fill screen RAM or colour RAM using Y." },
        "sta_izx": { hex:"81", bytes:2, cycles:6,  format:"STA ($zz,X)", mode:"(Indirect,X). Writes A via ZP pointer table.",                    use:"Write through a table of pointers in ZP." },
        "sta_izy": { hex:"91", bytes:2, cycles:6,  format:"STA ($zz),Y", mode:"(Indirect),Y. Writes A via ZP pointer + Y.",                     use:"Most common way to write through a ZP pointer." },

        "stx_zp":  { hex:"86", bytes:2, cycles:3,  format:"STX $zz",     mode:"Zero Page. Stores X to ZP.",                                      use:"Save X to a ZP variable." },
        "stx_zpy": { hex:"96", bytes:2, cycles:4,  format:"STX $zz,Y",   mode:"Zero Page,Y. Stores X to ZP + Y.",                               use:"Y-indexed ZP write from X." },
        "stx_abs": { hex:"8E", bytes:3, cycles:4,  format:"STX $hhll",   mode:"Absolute. Stores X to full address.",                             use:"Write X to a RAM variable or hardware port." },

        "sty_zp":  { hex:"84", bytes:2, cycles:3,  format:"STY $zz",     mode:"Zero Page. Stores Y to ZP.",                                      use:"Save Y to a ZP variable." },
        "sty_zpx": { hex:"94", bytes:2, cycles:4,  format:"STY $zz,X",   mode:"Zero Page,X. Stores Y to ZP + X.",                               use:"X-indexed ZP write from Y." },
        "sty_abs": { hex:"8C", bytes:3, cycles:4,  format:"STY $hhll",   mode:"Absolute. Stores Y to full address.",                             use:"Write Y to a RAM variable." },

        "tax":     { hex:"AA", bytes:1, cycles:2,  format:"TAX",         mode:"Implied. Copies A into X. A > X.",                               use:"Transfer result in A over to X for indexing." },
        "tay":     { hex:"A8", bytes:1, cycles:2,  format:"TAY",         mode:"Implied. Copies A into Y. A > Y.",                               use:"Transfer result in A over to Y for indexing." },
        "tsx":     { hex:"BA", bytes:1, cycles:2,  format:"TSX",         mode:"Implied. Copies Stack Pointer into X. SP > X.",                  use:"Read stack depth - useful for stack frame tricks." },
        "txa":     { hex:"8A", bytes:1, cycles:2,  format:"TXA",         mode:"Implied. Copies X into A. X > A.",                               use:"Move X result into A for arithmetic or storing." },
        "tya":     { hex:"98", bytes:1, cycles:2,  format:"TYA",         mode:"Implied. Copies Y into A. Y > A.",                               use:"Move Y result into A for arithmetic or storing." },
        "txs":     { hex:"9A", bytes:1, cycles:2,  format:"TXS",         mode:"Implied. Copies X into Stack Pointer. X > SP.",                  use:"Initialise the stack - do this once at startup." },

        "adc_imm": { hex:"69", bytes:2, cycles:2,  format:"ADC #$nn",    mode:"Immediate. Adds value + carry to A.",                             use:"Add a fixed number to A. Clear carry first (CLC)." },
        "adc_zp":  { hex:"65", bytes:2, cycles:3,  format:"ADC $zz",     mode:"Zero Page. Adds ZP value + carry to A.",                         use:"Add a ZP variable to A." },
        "adc_zpx": { hex:"75", bytes:2, cycles:4,  format:"ADC $zz,X",   mode:"Zero Page,X. Adds ZP+X value to A.",                             use:"Add indexed ZP value to A." },
        "adc_abs": { hex:"6D", bytes:3, cycles:4,  format:"ADC $hhll",   mode:"Absolute. Adds memory value + carry to A.",                      use:"Add a RAM variable to A." },
        "adc_abx": { hex:"7D", bytes:3, cycles:4,  format:"ADC $hhll,X", mode:"Absolute,X. Adds address+X to A.",                               use:"Add indexed table value to A." },
        "adc_aby": { hex:"79", bytes:3, cycles:4,  format:"ADC $hhll,Y", mode:"Absolute,Y. Adds address+Y to A.",                               use:"Add Y-indexed table value to A." },
        "adc_izx": { hex:"61", bytes:2, cycles:6,  format:"ADC ($zz,X)", mode:"(Indirect,X). Adds via ZP pointer table.",                       use:"Add through pointer table in ZP." },
        "adc_izy": { hex:"71", bytes:2, cycles:5,  format:"ADC ($zz),Y", mode:"(Indirect),Y. Adds via ZP pointer + Y.",                         use:"Add through ZP pointer." },

        "sbc_imm": { hex:"E9", bytes:2, cycles:2,  format:"SBC #$nn",    mode:"Immediate. Subtracts value + borrow from A.",                     use:"Subtract fixed number from A. Set carry first (SEC)." },
        "sbc_zp":  { hex:"E5", bytes:2, cycles:3,  format:"SBC $zz",     mode:"Zero Page. Subtracts ZP value from A.",                          use:"Subtract ZP variable from A." },
        "sbc_zpx": { hex:"F5", bytes:2, cycles:4,  format:"SBC $zz,X",   mode:"Zero Page,X. Subtracts ZP+X from A.",                            use:"Subtract indexed ZP value from A." },
        "sbc_abs": { hex:"ED", bytes:3, cycles:4,  format:"SBC $hhll",   mode:"Absolute. Subtracts memory value from A.",                       use:"Subtract RAM variable from A." },
        "sbc_abx": { hex:"FD", bytes:3, cycles:4,  format:"SBC $hhll,X", mode:"Absolute,X. Subtracts address+X from A.",                        use:"Subtract indexed table value from A." },
        "sbc_aby": { hex:"F9", bytes:3, cycles:4,  format:"SBC $hhll,Y", mode:"Absolute,Y. Subtracts address+Y from A.",                        use:"Subtract Y-indexed value from A." },
        "sbc_izx": { hex:"E1", bytes:2, cycles:6,  format:"SBC ($zz,X)", mode:"(Indirect,X). Subtracts via ZP pointer table.",                  use:"Subtract through pointer table." },
        "sbc_izy": { hex:"F1", bytes:2, cycles:5,  format:"SBC ($zz),Y", mode:"(Indirect),Y. Subtracts via ZP pointer + Y.",                    use:"Subtract through ZP pointer." },

        "inx":     { hex:"E8", bytes:1, cycles:2,  format:"INX",         mode:"Implied. Increments X by 1.",                                    use:"Loop counter. Compare with CPX to end loops." },
        "iny":     { hex:"C8", bytes:1, cycles:2,  format:"INY",         mode:"Implied. Increments Y by 1.",                                    use:"String/array index. Used in (ZP),Y walks." },
        "dex":     { hex:"CA", bytes:1, cycles:2,  format:"DEX",         mode:"Implied. Decrements X by 1.",                                    use:"Count-down loops. BNE after DEX for fast loop." },
        "dey":     { hex:"88", bytes:1, cycles:2,  format:"DEY",         mode:"Implied. Decrements Y by 1.",                                    use:"Count-down loops using Y." },
        "inc_zp":  { hex:"E6", bytes:2, cycles:5,  format:"INC $zz",     mode:"Zero Page. Increments memory at ZP by 1.",                       use:"Increment a ZP variable in place." },
        "inc_abs": { hex:"EE", bytes:3, cycles:6,  format:"INC $hhll",   mode:"Absolute. Increments memory at address by 1.",                   use:"Increment a RAM variable without loading to A." },
        "inc_abx": { hex:"FE", bytes:3, cycles:7,  format:"INC $hhll,X", mode:"Absolute,X. Increments memory at address+X.",                    use:"Increment a value inside an array." },
        "inc_zpx": { hex:"F6", bytes:2, cycles:6,  format:"INC $zz,X",   mode:"Zero Page,X. Increments ZP+X.",                                  use:"Increment indexed ZP value." },
        "dec_zp":  { hex:"C6", bytes:2, cycles:5,  format:"DEC $zz",     mode:"Zero Page. Decrements memory at ZP by 1.",                       use:"Decrement a ZP variable in place." },
        "dec_abs": { hex:"CE", bytes:3, cycles:6,  format:"DEC $hhll",   mode:"Absolute. Decrements memory at address by 1.",                   use:"Decrement a RAM variable without loading to A." },
        "dec_abx": { hex:"DE", bytes:3, cycles:7,  format:"DEC $hhll,X", mode:"Absolute,X. Decrements memory at address+X.",                    use:"Decrement a value inside an array." },
        "dec_zpx": { hex:"D6", bytes:2, cycles:6,  format:"DEC $zz,X",   mode:"Zero Page,X. Decrements ZP+X.",                                  use:"Decrement indexed ZP value." },

        "and_imm": { hex:"29", bytes:2, cycles:2,  format:"AND #$nn",    mode:"Immediate. Bitwise AND with A.",                                  use:"Mask bits in A. AND #$0F isolates lower nibble." },
        "and_zp":  { hex:"25", bytes:2, cycles:3,  format:"AND $zz",     mode:"Zero Page. Bitwise AND A with ZP value.",                        use:"Test or mask bits using a ZP variable." },
        "and_zpx": { hex:"35", bytes:2, cycles:4,  format:"AND $zz,X",   mode:"Zero Page,X. AND A with ZP+X.",                                  use:"Mask bits using indexed ZP value." },
        "and_abs": { hex:"2D", bytes:3, cycles:4,  format:"AND $hhll",   mode:"Absolute. Bitwise AND A with memory.",                           use:"Mask bits in A using RAM or hardware register." },
        "and_abx": { hex:"3D", bytes:3, cycles:4,  format:"AND $hhll,X", mode:"Absolute,X. AND A with address+X.",                              use:"Mask bits using indexed table value." },
        "and_aby": { hex:"39", bytes:3, cycles:4,  format:"AND $hhll,Y", mode:"Absolute,Y. AND A with address+Y.",                              use:"Mask bits using Y-indexed table value." },
        "and_izx": { hex:"21", bytes:2, cycles:6,  format:"AND ($zz,X)", mode:"(Indirect,X). AND via ZP pointer table.",                        use:"Mask through pointer table." },
        "and_izy": { hex:"31", bytes:2, cycles:5,  format:"AND ($zz),Y", mode:"(Indirect),Y. AND via ZP pointer + Y.",                          use:"Mask through ZP pointer." },

        "ora_imm": { hex:"09", bytes:2, cycles:2,  format:"ORA #$nn",    mode:"Immediate. Bitwise OR with A.",                                   use:"Set specific bits in A. ORA #$80 sets bit 7." },
        "ora_zp":  { hex:"05", bytes:2, cycles:3,  format:"ORA $zz",     mode:"Zero Page. Bitwise OR A with ZP value.",                         use:"Combine bit flags from a ZP variable." },
        "ora_zpx": { hex:"15", bytes:2, cycles:4,  format:"ORA $zz,X",   mode:"Zero Page,X. OR A with ZP+X.",                                   use:"Combine bits using indexed ZP." },
        "ora_abs": { hex:"0D", bytes:3, cycles:4,  format:"ORA $hhll",   mode:"Absolute. Bitwise OR A with memory.",                            use:"Set bits using hardware register or RAM value." },
        "ora_abx": { hex:"1D", bytes:3, cycles:4,  format:"ORA $hhll,X", mode:"Absolute,X. OR A with address+X.",                               use:"Set bits using indexed table value." },
        "ora_aby": { hex:"19", bytes:3, cycles:4,  format:"ORA $hhll,Y", mode:"Absolute,Y. OR A with address+Y.",                               use:"Set bits using Y-indexed value." },
        "ora_izx": { hex:"01", bytes:2, cycles:6,  format:"ORA ($zz,X)", mode:"(Indirect,X). OR via ZP pointer table.",                         use:"Combine bits through pointer table." },
        "ora_izy": { hex:"11", bytes:2, cycles:5,  format:"ORA ($zz),Y", mode:"(Indirect),Y. OR via ZP pointer + Y.",                           use:"Combine bits through ZP pointer." },

        "eor_imm": { hex:"49", bytes:2, cycles:2,  format:"EOR #$nn",    mode:"Immediate. Bitwise XOR with A.",                                  use:"Flip specific bits. EOR #$FF inverts all bits in A." },
        "eor_zp":  { hex:"45", bytes:2, cycles:3,  format:"EOR $zz",     mode:"Zero Page. XOR A with ZP value.",                                use:"Toggle bits using ZP variable." },
        "eor_zpx": { hex:"55", bytes:2, cycles:4,  format:"EOR $zz,X",   mode:"Zero Page,X. XOR A with ZP+X.",                                  use:"Toggle bits using indexed ZP." },
        "eor_abs": { hex:"4D", bytes:3, cycles:4,  format:"EOR $hhll",   mode:"Absolute. XOR A with memory.",                                   use:"Toggle bits using RAM or hardware value." },
        "eor_abx": { hex:"5D", bytes:3, cycles:4,  format:"EOR $hhll,X", mode:"Absolute,X. XOR A with address+X.",                              use:"Toggle bits using indexed table." },
        "eor_aby": { hex:"59", bytes:3, cycles:4,  format:"EOR $hhll,Y", mode:"Absolute,Y. XOR A with address+Y.",                              use:"Toggle bits using Y-indexed value." },
        "eor_izx": { hex:"41", bytes:2, cycles:6,  format:"EOR ($zz,X)", mode:"(Indirect,X). XOR via ZP pointer table.",                        use:"Toggle bits through pointer table." },
        "eor_izy": { hex:"51", bytes:2, cycles:5,  format:"EOR ($zz),Y", mode:"(Indirect),Y. XOR via ZP pointer + Y.",                          use:"Toggle bits through ZP pointer." },

        "bit_zp":  { hex:"24", bytes:2, cycles:3,  format:"BIT $zz",     mode:"Zero Page. Tests bits — sets N,V,Z flags only.",                  use:"Check bit 7/6 without changing A. Non-destructive test." },
        "bit_abs": { hex:"2C", bytes:3, cycles:4,  format:"BIT $hhll",   mode:"Absolute. Tests bits at address — flags only.",                   use:"Test VIC/CIA register bits without altering A." },

        "cmp_imm": { hex:"C9", bytes:2, cycles:2,  format:"CMP #$nn",    mode:"Immediate. Compares A with value, sets flags.",                   use:"Check if A equals a value. Follow with BEQ/BNE." },
        "cmp_zp":  { hex:"C5", bytes:2, cycles:3,  format:"CMP $zz",     mode:"Zero Page. Compares A with ZP value.",                           use:"Compare A against a ZP variable." },
        "cmp_zpx": { hex:"D5", bytes:2, cycles:4,  format:"CMP $zz,X",   mode:"Zero Page,X. Compares A with ZP+X.",                             use:"Compare A against indexed ZP value." },
        "cmp_abs": { hex:"CD", bytes:3, cycles:4,  format:"CMP $hhll",   mode:"Absolute. Compares A with memory value.",                        use:"Compare A against a RAM variable." },
        "cmp_abx": { hex:"DD", bytes:3, cycles:4,  format:"CMP $hhll,X", mode:"Absolute,X. Compares A with address+X.",                         use:"Compare A against indexed table value." },
        "cmp_aby": { hex:"D9", bytes:3, cycles:4,  format:"CMP $hhll,Y", mode:"Absolute,Y. Compares A with address+Y.",                         use:"Compare A against Y-indexed value." },
        "cmp_izx": { hex:"C1", bytes:2, cycles:6,  format:"CMP ($zz,X)", mode:"(Indirect,X). Compare via pointer table.",                       use:"Compare through pointer table." },
        "cmp_izy": { hex:"D1", bytes:2, cycles:5,  format:"CMP ($zz),Y", mode:"(Indirect),Y. Compare via ZP pointer + Y.",                      use:"Compare through ZP pointer." },

        "cpx_imm": { hex:"E0", bytes:2, cycles:2,  format:"CPX #$nn",    mode:"Immediate. Compares X with value.",                               use:"End-of-loop check. CPX #count then BNE." },
        "cpx_zp":  { hex:"E4", bytes:2, cycles:3,  format:"CPX $zz",     mode:"Zero Page. Compares X with ZP value.",                           use:"Compare X against a ZP variable." },
        "cpx_abs": { hex:"EC", bytes:3, cycles:4,  format:"CPX $hhll",   mode:"Absolute. Compares X with memory.",                              use:"Compare X against a RAM variable." },
        "cpy_imm": { hex:"C0", bytes:2, cycles:2,  format:"CPY #$nn",    mode:"Immediate. Compares Y with value.",                               use:"End-of-loop check using Y." },
        "cpy_zp":  { hex:"C4", bytes:2, cycles:3,  format:"CPY $zz",     mode:"Zero Page. Compares Y with ZP value.",                           use:"Compare Y against a ZP variable." },
        "cpy_abs": { hex:"CC", bytes:3, cycles:4,  format:"CPY $hhll",   mode:"Absolute. Compares Y with memory.",                              use:"Compare Y against a RAM variable." },

		"asl_a":   { hex:"0A", bytes:1, cycles:2,  format:"ASL A",       mode:"Accumulator. Shifts A left 1 bit. Bit 7 > carry.",               use:"Multiply A by 2. Fast bit extraction." },
        "asl_zp":  { hex:"06", bytes:2, cycles:5,  format:"ASL $zz",     mode:"Zero Page. Shifts ZP left 1 bit.",                               use:"Multiply ZP variable by 2 in place." },
        "asl_zpx": { hex:"16", bytes:2, cycles:6,  format:"ASL $zz,X",   mode:"Zero Page,X. Shifts ZP+X left.",                                 use:"Multiply indexed ZP value by 2." },
        "asl_abs": { hex:"0E", bytes:3, cycles:6,  format:"ASL $hhll",   mode:"Absolute. Shifts memory left 1 bit.",                            use:"Multiply RAM value by 2 in place." },
        "asl_abx": { hex:"1E", bytes:3, cycles:7,  format:"ASL $hhll,X", mode:"Absolute,X. Shifts address+X left.",                             use:"Shift value in array left." },
        "lsr_a":   { hex:"4A", bytes:1, cycles:2,  format:"LSR A",       mode:"Accumulator. Shifts A right 1 bit. Bit 0 > carry.",              use:"Divide A by 2. Extract low bit." },
        "lsr_zp":  { hex:"46", bytes:2, cycles:5,  format:"LSR $zz",     mode:"Zero Page. Shifts ZP right 1 bit.",                              use:"Divide ZP variable by 2 in place." },
        "lsr_zpx": { hex:"56", bytes:2, cycles:6,  format:"LSR $zz,X",   mode:"Zero Page,X. Shifts ZP+X right.",                                use:"Divide indexed ZP value by 2." },
        "lsr_abs": { hex:"4E", bytes:3, cycles:6,  format:"LSR $hhll",   mode:"Absolute. Shifts memory right 1 bit.",                           use:"Divide RAM value by 2 in place." },
        "lsr_abx": { hex:"5E", bytes:3, cycles:7,  format:"LSR $hhll,X", mode:"Absolute,X. Shifts address+X right.",                            use:"Divide array value by 2." },
        "rol_a":   { hex:"2A", bytes:1, cycles:2,  format:"ROL A",       mode:"Accumulator. Rotates A left through carry. Bit 7 > carry > bit 0.", use:"Multi-byte shift left chain." },
        "rol_zp":  { hex:"26", bytes:2, cycles:5,  format:"ROL $zz",     mode:"Zero Page. Rotates ZP left through carry.",                      use:"Multi-byte shift on ZP variable." },
        "rol_zpx": { hex:"36", bytes:2, cycles:6,  format:"ROL $zz,X",   mode:"Zero Page,X. Rotates ZP+X left.",                                use:"Rotate indexed ZP value." },
        "rol_abs": { hex:"2E", bytes:3, cycles:6,  format:"ROL $hhll",   mode:"Absolute. Rotates memory left through carry.",                   use:"Multi-byte shift on RAM variable." },
        "rol_abx": { hex:"3E", bytes:3, cycles:7,  format:"ROL $hhll,X", mode:"Absolute,X. Rotates address+X left.",                            use:"Rotate value in array." },
        "ror_a":   { hex:"6A", bytes:1, cycles:2,  format:"ROR A",       mode:"Accumulator. Rotates A right through carry. Bit 0 > carry > bit 7.", use:"Multi-byte shift right chain." },
        "ror_zp":  { hex:"66", bytes:2, cycles:5,  format:"ROR $zz",     mode:"Zero Page. Rotates ZP right through carry.",                     use:"Multi-byte shift on ZP variable." },
        "ror_zpx": { hex:"76", bytes:2, cycles:6,  format:"ROR $zz,X",   mode:"Zero Page,X. Rotates ZP+X right.",                               use:"Rotate indexed ZP value." },
        "ror_abs": { hex:"6E", bytes:3, cycles:6,  format:"ROR $hhll",   mode:"Absolute. Rotates memory right through carry.",                  use:"Multi-byte shift on RAM variable." },
        "ror_abx": { hex:"7E", bytes:3, cycles:7,  format:"ROR $hhll,X", mode:"Absolute,X. Rotates address+X right.",                           use:"Rotate value in array." },

        "jmp_abs": { hex:"4C", bytes:3, cycles:3,  format:"JMP $hhll",   mode:"Absolute. Jumps to 16-bit address unconditionally.",              use:"Goto. Jump to a label or fixed address." },
        "jmp_ind": { hex:"6C", bytes:3, cycles:5,  format:"JMP ($hhll)", mode:"Indirect. Jumps to address stored at pointer.",                   use:"Jump table dispatch. Beware $xxFF page wrap bug." },
        "jsr":     { hex:"20", bytes:3, cycles:6,  format:"JSR $hhll",   mode:"Absolute. Calls subroutine, pushes return address.",              use:"Call a function. Must end with RTS." },
        "rts":     { hex:"60", bytes:1, cycles:6,  format:"RTS",         mode:"Implied. Returns from subroutine.",                               use:"End of a JSR subroutine. Pops return address." },
        "rti":     { hex:"40", bytes:1, cycles:6,  format:"RTI",         mode:"Implied. Returns from interrupt handler.",                        use:"End of IRQ/NMI handler. Restores flags + PC." },

        "bne":     { hex:"D0", bytes:2, cycles:2,  format:"BNE label",   mode:"Relative. Branches if Zero flag clear (not equal).",              use:"Loop until zero or skip when values differ." },
        "beq":     { hex:"F0", bytes:2, cycles:2,  format:"BEQ label",   mode:"Relative. Branches if Zero flag set (equal).",                    use:"Branch when CMP/CPX/CPY finds a match." },
        "bcc":     { hex:"90", bytes:2, cycles:2,  format:"BCC label",   mode:"Relative. Branches if Carry flag clear.",                         use:"Branch on less-than after CMP, or no overflow after ADC." },
        "bcs":     { hex:"B0", bytes:2, cycles:2,  format:"BCS label",   mode:"Relative. Branches if Carry flag set.",                           use:"Branch on greater-or-equal after CMP." },
        "bpl":     { hex:"10", bytes:2, cycles:2,  format:"BPL label",   mode:"Relative. Branches if Negative flag clear (positive).",           use:"Branch when result is positive / bit 7 clear." },
        "bmi":     { hex:"30", bytes:2, cycles:2,  format:"BMI label",   mode:"Relative. Branches if Negative flag set.",                        use:"Branch when result is negative / bit 7 set." },
        "bvc":     { hex:"50", bytes:2, cycles:2,  format:"BVC label",   mode:"Relative. Branches if Overflow flag clear.",                      use:"Branch when no signed overflow occurred." },
        "bvs":     { hex:"70", bytes:2, cycles:2,  format:"BVS label",   mode:"Relative. Branches if Overflow flag set.",                        use:"Branch when signed overflow occurred." },

        "clc":     { hex:"18", bytes:1, cycles:2,  format:"CLC",         mode:"Implied. Clears Carry flag.",                                     use:"Always do before ADC to prevent stale carry." },
        "sec":     { hex:"38", bytes:1, cycles:2,  format:"SEC",         mode:"Implied. Sets Carry flag.",                                       use:"Always do before SBC to borrow correctly." },
        "sei":     { hex:"78", bytes:1, cycles:2,  format:"SEI",         mode:"Implied. Disables IRQ interrupts.",                               use:"Protect critical code sections from IRQ firing." },
        "cli":     { hex:"58", bytes:1, cycles:2,  format:"CLI",         mode:"Implied. Enables IRQ interrupts.",                                use:"Re-enable IRQs after setup is complete." },
        "clv":     { hex:"B8", bytes:1, cycles:2,  format:"CLV",         mode:"Implied. Clears Overflow flag.",                                  use:"Rarely needed — resets V flag before BVC/BVS." },
        "cld":     { hex:"D8", bytes:1, cycles:2,  format:"CLD",         mode:"Implied. Clears Decimal mode flag.",                              use:"Ensure binary arithmetic mode - do at startup." },
        "sed":     { hex:"F8", bytes:1, cycles:2,  format:"SED",         mode:"Implied. Sets Decimal mode flag.",                                use:"Enable BCD arithmetic mode (rare on C64)." },
        "pha":     { hex:"48", bytes:1, cycles:3,  format:"PHA",         mode:"Implied. Pushes A onto the stack.",                               use:"Save A before calling subroutine or IRQ entry." },
        "pla":     { hex:"68", bytes:1, cycles:4,  format:"PLA",         mode:"Implied. Pulls A from the stack.",                                use:"Restore A after subroutine or at IRQ exit." },
        "php":     { hex:"08", bytes:1, cycles:3,  format:"PHP",         mode:"Implied. Pushes Processor Status onto stack.",                    use:"Save all flags before a critical section." },
        "plp":     { hex:"28", bytes:1, cycles:4,  format:"PLP",         mode:"Implied. Pulls Processor Status from stack.",                     use:"Restore all flags saved with PHP." },

        "lax_zp":  { hex:"A7", bytes:2, cycles:3,  format:"LAX $zz",     mode:"Illegal. Loads both A and X from ZP simultaneously.",             use:"Saves an extra LDX - load pointer and index at once." },
        "sax_zp":  { hex:"87", bytes:2, cycles:3,  format:"SAX $zz",     mode:"Illegal. Stores A AND X to ZP (bitwise AND result).",             use:"Store combined A&X mask to ZP in one byte." },
        "dcp_abs": { hex:"CF", bytes:3, cycles:6,  format:"DCP $hhll",   mode:"Illegal. Decrements memory then CMPs with A.",                    use:"Saves separate DEC+CMP — common in timing loops." },
        "isc_abs": { hex:"EF", bytes:3, cycles:6,  format:"ISC $hhll",   mode:"Illegal. Increments memory then SBCs from A.",                    use:"Saves separate INC+SBC." },
        "rla_abs": { hex:"2F", bytes:3, cycles:6,  format:"RLA $hhll",   mode:"Illegal. ROLs memory then ANDs with A.",                          use:"Compact bit-shift-and-mask in one instruction." },
        "slo_abs": { hex:"0F", bytes:3, cycles:6,  format:"SLO $hhll",   mode:"Illegal. ASLs memory then ORAs with A.",                          use:"Shift memory left and combine into A at once." },
        "sre_abs": { hex:"4F", bytes:3, cycles:6,  format:"SRE $hhll",   mode:"Illegal. LSRs memory then EORs with A.",                          use:"Shift right and XOR into A in one op." },
    };

    if (variable_struct_exists(_map, _key)) {
        return _map[$ _key];
    }
    return undefined;
}